### ISSUE TITLE
Using reloadInterval option causes crash

### ISSUE THREAD

**Issue by dylanseago** [locize/i18next-node-locize-backend#1]
Setting the `reloadInterval` option causes the following error after the interval elapses the first time:
```
/my-project/node_modules/i18next-node-locize-backend/lib/index.js:107
          backendConnector = _services.backendConnector,
                                       ^

TypeError: Cannot read property 'backendConnector' of undefined
    at Backend.reload (/my-project/node_modules/i18next-node-locize-backend/lib/index.js:107:40)
    at Timeout._onTimeout (/my-project/node_modules/i18next-node-locize-backend/lib/index.js:97:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

Full config:
```js
{ debug: true,
  initImmediate: false,
  ns: [ 'app', 'common' ],
  defaultNS: 'app',
  fallbackLng: [ 'en' ],
  fallbackNS: false,
  whitelist: [ 'en', 'fr', 'cimode' ],
  nonExplicitWhitelist: true,
  load: 'languageOnly',
  preload: [ 'en', 'fr' ],
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  saveMissing: true,
  updateMissing: false,
  saveMissingTo: 'current',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: [Function: returnedObjectHandler],
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: handle],
  interpolation:
   { escapeValue: true,
     format: [Function: format],
     prefix: '{{',
     suffix: '}}',
     formatSeparator: ',',
     unescapePrefix: '-',
     nestingPrefix: '$t(',
     nestingSuffix: ')',
     maxReplaces: 1000 },
  backend:
   { projectId: '[redacted]',
     version: 'latest',
     apiKey: '[redacted]',
     referenceLng: 'en',
     reloadInterval: 15000 },
  detection:
   { lookupQuerystring: 'lng',
     order: [ 'querystring', 'cookie', 'header' ],
     lookupCookie: 'i18next',
     lookupSession: 'lng',
     lookupFromPathIndex: 0,
     caches: false },
  isClone: true }
```

Using versions:
```
node@8.9.4
i18next@10.6.0
i18next-express-middleware@1.1.1
i18next-node-locize-backend@2.2.1
```

**Comment by jamuhl** [comment]
sorry for that .... should be fixed in i18next-node-locize-backend@2.2.2
